import test from "node:test";
import assert from "node:assert/strict";
import { buildExecutiveReport } from "../src/lib/reports.ts";

const now = new Date("2026-03-14T10:00:00.000Z");

test("buildExecutiveReport aggregates portfolio, risk and capacity metrics", () => {
  const report = buildExecutiveReport(
    [
      {
        id: "project_1",
        name: "Northstar",
        description: null,
        color: "#2563eb",
        status: "ACTIVE",
        type: "WEBSITE",
        priority: "HIGH",
        tags: [],
        startDate: null,
        dueDate: new Date("2026-03-16T00:00:00.000Z"),
        createdAt: new Date("2026-03-01T00:00:00.000Z"),
        updatedAt: new Date("2026-03-13T00:00:00.000Z"),
        owner: { id: "user_1", name: "Tarik", email: "tarik@synorq.com" },
        client: { id: "client_1", name: "Northstar", health: "WATCH" },
        tasks: [
          {
            id: "task_1",
            title: "Launch",
            status: "DONE",
            dueDate: new Date("2026-03-12T00:00:00.000Z"),
            completedAt: new Date("2026-03-13T00:00:00.000Z"),
            assigneeId: "user_1",
            createdAt: new Date("2026-03-01T00:00:00.000Z"),
            updatedAt: new Date("2026-03-13T00:00:00.000Z"),
            priority: "HIGH",
          },
        ],
        milestones: [],
        risks: [],
        totalTasks: 1,
        completedTasks: 1,
        openTasks: 0,
        overdueTasks: 0,
        dueThisWeekTasks: 0,
        unassignedTasks: 0,
        completionRate: 100,
        activeAssignees: 0,
        health: { key: "good", label: "Saglikli", tone: "", score: 95 },
        dueDateResolved: new Date("2026-03-16T00:00:00.000Z"),
        dueInDays: 2,
        lastActivityAt: new Date("2026-03-13T00:00:00.000Z"),
        openMilestones: 0,
        completedMilestones: 0,
        milestoneCompletionRate: 0,
        nextMilestone: null,
        openRisks: 0,
        criticalRisks: 0,
      },
      {
        id: "project_2",
        name: "Helio",
        description: null,
        color: "#ea580c",
        status: "ACTIVE",
        type: "RETAINER",
        priority: "URGENT",
        tags: [],
        startDate: null,
        dueDate: new Date("2026-03-15T00:00:00.000Z"),
        createdAt: new Date("2026-03-02T00:00:00.000Z"),
        updatedAt: new Date("2026-03-13T00:00:00.000Z"),
        owner: { id: "user_2", name: "Elif", email: "elif@synorq.com" },
        client: { id: "client_2", name: "Helio", health: "AT_RISK" },
        tasks: [
          {
            id: "task_2",
            title: "SEO fix",
            status: "IN_PROGRESS",
            dueDate: new Date("2026-03-14T00:00:00.000Z"),
            completedAt: null,
            assigneeId: "user_2",
            createdAt: new Date("2026-03-03T00:00:00.000Z"),
            updatedAt: new Date("2026-03-13T00:00:00.000Z"),
            priority: "URGENT",
          },
        ],
        milestones: [],
        risks: [],
        totalTasks: 1,
        completedTasks: 0,
        openTasks: 1,
        overdueTasks: 1,
        dueThisWeekTasks: 1,
        unassignedTasks: 0,
        completionRate: 0,
        activeAssignees: 1,
        health: { key: "risk", label: "Riskli", tone: "", score: 48 },
        dueDateResolved: new Date("2026-03-15T00:00:00.000Z"),
        dueInDays: 1,
        lastActivityAt: new Date("2026-03-13T00:00:00.000Z"),
        openMilestones: 1,
        completedMilestones: 0,
        milestoneCompletionRate: 0,
        nextMilestone: {
          id: "milestone_1",
          title: "Review pack",
          status: "AT_RISK",
          dueDate: new Date("2026-03-15T00:00:00.000Z"),
        },
        openRisks: 2,
        criticalRisks: 1,
      },
    ],
    [
      {
        id: "user_1",
        name: "Tarik",
        email: "tarik@synorq.com",
        image: null,
        role: "ADMIN",
        weeklyCapacityHours: 30,
        projectedHours: 18,
        loggedHours: 5,
        availableHours: 12,
        utilization: 60,
        activeTasks: 2,
        overdueTasks: 0,
        dueThisWeekTasks: 1,
        blockedTasks: 0,
        completedLast7Days: 2,
        loadState: "balanced",
        upcomingTasks: [],
      },
      {
        id: "user_2",
        name: "Elif",
        email: "elif@synorq.com",
        image: null,
        role: "MEMBER",
        weeklyCapacityHours: 34,
        projectedHours: 31,
        loggedHours: 8,
        availableHours: 3,
        utilization: 91,
        activeTasks: 4,
        overdueTasks: 1,
        dueThisWeekTasks: 3,
        blockedTasks: 1,
        completedLast7Days: 1,
        loadState: "overloaded",
        upcomingTasks: [],
      },
    ],
    [
      { id: "activity_1", action: "task.updated", createdAt: new Date("2026-03-13T00:00:00.000Z") },
      { id: "activity_2", action: "risk.created", createdAt: new Date("2026-03-12T00:00:00.000Z") },
    ],
    now
  );

  assert.equal(report.summary.projectCount, 2);
  assert.equal(report.summary.riskProjects, 1);
  assert.equal(report.summary.deliveriesThisWeek, 2);
  assert.equal(report.summary.completedLast7Days, 1);
  assert.equal(report.summary.utilization, 77);
  assert.equal(report.summary.overloadedMembers, 1);
  assert.equal(report.clientHealth.AT_RISK, 1);
  assert.equal(report.projectSpotlights.highestRisk?.name, "Helio");
});
